# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         last
version:      v0.0.1
version_from: lib/last.pm
installdirs:  site
requires:
    first:                         0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
